-- ============================================================
-- ARCHIVIO STORICO — recuperato dalla sidebar dell'SQL Editor di
-- Supabase il 13/08/2026, non prima presente nel repo (vedi CLAUDE.md).
-- NON RIESEGUIRE: lo schema reale è cambiato moltissimo da allora
-- (multi-tenancy, RLS con is_gestore_lega, ecc.) — vedi migrations/
-- per lo stato attuale. Tenuto solo come documentazione storica.
-- ============================================================

-- ============================================================
-- MONDAY LEAGUE — Schema Supabase v1
-- Calibrato sui campi reali dell'export Fubles (test 5 partite)
-- Predisposto multi-lega fin dall'inizio
-- Eseguire nell'SQL Editor di Supabase, PRIMA di seed_test5.sql
-- ============================================================

-- ---------- LEGHE ----------
create table leghe (
  id          bigint generated by default as identity primary key,
  nome        text not null,
  slug        text not null unique,          -- es. 'monday-league'
  struttura   text,                          -- campo abituale
  citta       text,
  created_at  timestamptz not null default now()
);

-- ---------- GIOCATORI ----------
create table giocatori (
  id                  bigint generated by default as identity primary key,
  lega_id             bigint not null references leghe(id) on delete cascade,
  nome                text not null,          -- come appare su Fubles
  fubles_user_id      text,                   -- es. '554647' (da URL profilo)
  fubles_url          text,
  ruolo_prevalente    text check (ruolo_prevalente in ('POR','DIF','CEN','ATT')),
  foto_url            text,
  foto_disponibile    boolean not null default false,
  -- privacy: di default nessun dato visibile fuori dalla lega.
  -- Diventa true solo con consenso esplicito del giocatore (fase multi-lega).
  visibilita_pubblica boolean not null default false,
  attivo              boolean not null default true,
  note                text,
  created_at          timestamptz not null default now(),
  unique (lega_id, fubles_user_id)
);

-- ---------- PARTITE ----------
create table partite (
  id               bigint generated by default as identity primary key,
  lega_id          bigint not null references leghe(id) on delete cascade,
  match_id         text not null unique,      -- YYYY-MM-DD_STRUTTURA_SQ1-SQ2 (chiave anti-duplicati import)
  fubles_match_id  text,                       -- es. '3149865'
  fubles_url       text,
  data             date not null,
  ora              time,
  disciplina       text,                       -- 'Calcio a 8'
  coperto_scoperto text,
  struttura        text,
  indirizzo        text,
  organizzatore    text,
  squadra_1        text not null,
  squadra_2        text not null,
  gol_squadra_1    smallint not null,
  gol_squadra_2    smallint not null,
  forza_squadra_1  smallint,                   -- valore pre-partita Fubles
  forza_squadra_2  smallint,
  stato            text default 'Disputata',
  pubblica_privata text,
  importata_il     timestamptz not null default now()
);

-- ---------- PRESTAZIONI ----------
create table prestazioni (
  id            bigint generated by default as identity primary key,
  partita_id    bigint not null references partite(id) on delete cascade,
  giocatore_id  bigint not null references giocatori(id) on delete cascade,
  squadra       text not null,
  ruolo         text,                          -- ruolo in QUELLA partita (può variare)
  voto          numeric(4,2),                  -- media Fubles, null se non votato
  gol           smallint not null default 0,   -- ⚠ attribuzione parziale su Fubles
  motm          boolean not null default false,
  premio        text,
  esito         text check (esito in ('Vittoria','Pareggio','Sconfitta')),
  gol_squadra   smallint,
  gol_subiti    smallint,
  note          text,
  unique (partita_id, giocatore_id)
);

-- ---------- VOTI INDIVIDUALI ----------
create table voti_ricevuti (
  id           bigint generated by default as identity primary key,
  partita_id   bigint not null references partite(id) on delete cascade,
  valutato_id  bigint not null references giocatori(id) on delete cascade,
  votante_id   bigint not null references giocatori(id) on delete cascade,
  voto         numeric(4,2) not null,
  commento     text,
  -- flag per voti fuori scala (es. il 10 di Oscar Yu): esclusi dalle medie "pulite"
  anomalo      boolean not null default false,
  unique (partita_id, valutato_id, votante_id)
);

-- ---------- LOG IMPORT ----------
create table import_log (
  id             bigint generated by default as identity primary key,
  eseguito_il    timestamptz not null default now(),
  fonte          text,                         -- 'claude-chrome', 'csv', 'api'
  n_partite      int,
  n_prestazioni  int,
  n_voti         int,
  errori         text
);

-- ---------- INDICI ----------
create index idx_prestazioni_giocatore on prestazioni (giocatore_id);
create index idx_prestazioni_partita   on prestazioni (partita_id);
create index idx_voti_valutato         on voti_ricevuti (valutato_id);
create index idx_partite_lega_data     on partite (lega_id, data desc);

-- ---------- VISTA CLASSIFICA ----------
-- Punti: vittoria 3, pareggio 1, sconfitta 0 (modificabile qui in un punto solo)
create or replace view v_classifica as
select
  g.lega_id,
  g.id as giocatore_id,
  g.nome,
  g.ruolo_prevalente,
  count(pr.id)                                            as presenze,
  count(*) filter (where pr.esito = 'Vittoria')           as vittorie,
  count(*) filter (where pr.esito = 'Pareggio')           as pareggi,
  count(*) filter (where pr.esito = 'Sconfitta')          as sconfitte,
  count(*) filter (where pr.esito = 'Vittoria') * 3
    + count(*) filter (where pr.esito = 'Pareggio')       as punti,
  coalesce(sum(pr.gol), 0)                                as gol,
  round(avg(pr.voto), 2)                                  as media_voto,
  count(*) filter (where pr.motm)                         as mvp
from giocatori g
join prestazioni pr on pr.giocatore_id = g.id
group by g.lega_id, g.id, g.nome, g.ruolo_prevalente;

-- ---------- VISTA MEDIE VOTI INDIVIDUALI (senza anomali) ----------
create or replace view v_voti_puliti as
select
  v.valutato_id,
  v.votante_id,
  count(*)             as n_voti,
  round(avg(v.voto),2) as media
from voti_ricevuti v
where not v.anomalo
group by v.valutato_id, v.votante_id;

-- ---------- ROW LEVEL SECURITY ----------
-- Abilitata subito: nulla è leggibile senza policy.
-- Per la fase di test con solo il tuo accesso admin va già bene così
-- (la service key bypassa RLS). Le policy per i membri arrivano con Supabase Auth.
alter table leghe          enable row level security;
alter table giocatori      enable row level security;
alter table partite        enable row level security;
alter table prestazioni    enable row level security;
alter table voti_ricevuti  enable row level security;
alter table import_log     enable row level security;

-- Lettura per utenti autenticati (da raffinare per-lega quando attiviamo Auth)
create policy "lettura autenticati" on leghe         for select to authenticated using (true);
create policy "lettura autenticati" on giocatori     for select to authenticated using (true);
create policy "lettura autenticati" on partite       for select to authenticated using (true);
create policy "lettura autenticati" on prestazioni   for select to authenticated using (true);
create policy "lettura autenticati" on voti_ricevuti for select to authenticated using (true);