-- ============================================================
-- SCARSI LEAGUE — Migrazione v0.9 "La Stagione"
-- Stagioni, dati manuali post-partita, premi
-- Eseguire nell'SQL Editor di Supabase dopo v07_piattaforma.sql
-- ============================================================

-- ---------- STAGIONI ----------
create table if not exists stagioni (
  id         bigint generated by default as identity primary key,
  lega_id    bigint not null references leghe(id) on delete cascade,
  nome       text not null,               -- es. "2026/27"
  inizio     date not null,
  fine       date,                        -- null = stagione in corso
  attiva     boolean not null default false,
  created_at timestamptz not null default now()
);

alter table partite add column if not exists stagione_id bigint references stagioni(id);

-- stagione zero (le partite di test già importate, primavera-estate 2026)
insert into stagioni (lega_id, nome, inizio, fine, attiva)
  select 1, 'Estate 2026', '2026-06-01', '2026-08-31', false
  where not exists (select 1 from stagioni where lega_id = 1 and nome = 'Estate 2026');

-- stagione nuova, quella che parte a settembre (nasce vuota apposta)
insert into stagioni (lega_id, nome, inizio, attiva)
  select 1, '2026/27', '2026-09-01', true
  where not exists (select 1 from stagioni where lega_id = 1 and nome = '2026/27');

-- assegna le partite esistenti alla stagione estiva
update partite p set stagione_id = s.id
  from stagioni s
  where p.stagione_id is null and s.lega_id = p.lega_id
    and p.data between s.inizio and coalesce(s.fine, '2999-12-31');

-- ---------- DATI MANUALI POST-PARTITA ----------
-- Fubles non espone assist, miglior portiere, cartellini: li inserisce l'admin.
create table if not exists dati_manuali (
  id           bigint generated by default as identity primary key,
  partita_id   bigint not null references partite(id) on delete cascade,
  giocatore_id bigint not null references giocatori(id) on delete cascade,
  assist       smallint not null default 0,
  clean_sheet  boolean not null default false,
  gol_subiti   smallint,
  cartellini   smallint not null default 0,
  autogol      smallint not null default 0,
  note         text,
  unique (partita_id, giocatore_id)
);

-- premi assegnati manualmente (settimanali/mensili/stagionali)
create table if not exists premi (
  id           bigint generated by default as identity primary key,
  lega_id      bigint not null references leghe(id) on delete cascade,
  stagione_id  bigint references stagioni(id),
  partita_id   bigint references partite(id) on delete cascade,
  giocatore_id bigint not null references giocatori(id) on delete cascade,
  tipo         text not null,     -- es. 'miglior_portiere','gol_del_mese','bidone_oro'
  periodo      text,              -- 'partita' | 'mese' | 'stagione'
  etichetta    text,              -- testo mostrato, es. "Miglior Portiere"
  emoji        text,
  note         text,
  assegnato_il timestamptz not null default now()
);

create index if not exists idx_dati_manuali_partita on dati_manuali (partita_id);
create index if not exists idx_premi_giocatore on premi (giocatore_id);
create index if not exists idx_partite_stagione on partite (stagione_id);

-- ---------- RLS ----------
alter table stagioni      enable row level security;
alter table dati_manuali  enable row level security;
alter table premi         enable row level security;

-- lettura per i membri approvati (stesso criterio delle altre tabelle)
create policy "lettura membri" on stagioni for select to authenticated
  using (exists (select 1 from membri_autorizzati m where m.email = lower(auth.jwt() ->> 'email')));
create policy "lettura membri" on dati_manuali for select to authenticated
  using (exists (select 1 from membri_autorizzati m where m.email = lower(auth.jwt() ->> 'email')));
create policy "lettura membri" on premi for select to authenticated
  using (exists (select 1 from membri_autorizzati m where m.email = lower(auth.jwt() ->> 'email')));

-- scrittura riservata all'admin
create policy "admin scrive stagioni" on stagioni for all to authenticated
  using (is_admin()) with check (is_admin());
create policy "admin scrive dati manuali" on dati_manuali for all to authenticated
  using (is_admin()) with check (is_admin());
create policy "admin scrive premi" on premi for all to authenticated
  using (is_admin()) with check (is_admin());

-- ---------- RLS aggiuntive per la Fase 3-bis (gestione admin) ----------
-- schema.sql aveva creato solo policy di lettura su queste tabelle:
-- l'admin non poteva scrivere nulla dal pannello (l'import usa la
-- service key e bypassa RLS). Qui aggiungiamo la scrittura admin,
-- necessaria per eliminare/spostare partite e i dati collegati.
create policy "admin scrive partite" on partite for all to authenticated
  using (is_admin()) with check (is_admin());
create policy "admin scrive prestazioni" on prestazioni for all to authenticated
  using (is_admin()) with check (is_admin());
create policy "admin scrive voti_ricevuti" on voti_ricevuti for all to authenticated
  using (is_admin()) with check (is_admin());

-- import_log aveva RLS abilitata ma nessuna policy (scrivibile solo
-- con service key): serve una policy per loggare le operazioni fatte
-- dal pannello admin (Fase 3-bis, traccia delle eliminazioni).
create policy "admin gestisce import_log" on import_log for all to authenticated
  using (is_admin()) with check (is_admin());
