-- ============================================================
-- SCARSI LEAGUE — Migrazione v1.15 — dashboard organizzatore
-- Eseguire nell'SQL Editor di Supabase dopo v20.sql
--
-- Dati privati per giocatore che oggi non hanno nessun posto dove
-- stare: affidabilità (quanto si presenta chi si iscrive), no-show
-- (quante volte ha dato buca), note libere dell'organizzatore. Un
-- record per giocatore, non uno storico — si aggiorna, non si accumula.
--
-- Deve restare invisibile ai membri normali: solo chi gestisce la
-- lega (admin o coorganizzatore, is_gestore_lega) può leggerlo o
-- scriverlo — nessuna policy "lettura membri", stesso principio di
-- backup_snapshot (v18.sql) ma con il gate di lega invece che
-- super-admin.
-- ============================================================

create table if not exists dati_organizzativi (
  id              bigint generated by default as identity primary key,
  giocatore_id    bigint not null references giocatori(id) on delete cascade,
  lega_id         bigint not null references leghe(id) on delete cascade,
  affidabilita    smallint check (affidabilita between 1 and 5),
  no_show_count   smallint not null default 0,
  note            text,
  aggiornato_il   timestamptz not null default now(),
  unique (giocatore_id)
);

alter table dati_organizzativi enable row level security;

do $$
declare pol record;
begin
  for pol in select policyname from pg_policies where schemaname = 'public'
    and tablename = 'dati_organizzativi' loop
    execute format('drop policy %I on dati_organizzativi', pol.policyname);
  end loop;
end $$;

create policy "solo gestore legge dati organizzativi" on dati_organizzativi
  for select to authenticated using (is_gestore_lega(lega_id));
create policy "solo gestore scrive dati organizzativi" on dati_organizzativi
  for all to authenticated using (is_gestore_lega(lega_id)) with check (is_gestore_lega(lega_id));

-- elimina_lega() ripulisce anche questa tabella, prima di giocatori —
-- stessa filosofia di v12.sql: cancellazione esplicita in ordine di
-- dipendenza, non ci si affida solo al vincolo di chiave esterna
-- (anche se qui è comunque "on delete cascade", per prudenza doppia
-- dopo il bug corretto in v20.sql).
create or replace function elimina_lega(p_lega_id bigint) returns text
language plpgsql security definer as $$
begin
  if not is_admin_lega(p_lega_id) then return 'Non autorizzato'; end if;

  delete from voti_ricevuti where partita_id in (select id from partite where lega_id = p_lega_id);
  delete from dati_manuali where partita_id in (select id from partite where lega_id = p_lega_id);
  delete from prestazioni where partita_id in (select id from partite where lega_id = p_lega_id);
  delete from premi where lega_id = p_lega_id;
  delete from partite where lega_id = p_lega_id;
  delete from stagioni where lega_id = p_lega_id;
  delete from membri_autorizzati where lega_id = p_lega_id;
  delete from richieste_accesso where lega_id = p_lega_id;
  delete from dati_organizzativi where lega_id = p_lega_id;
  delete from giocatori where lega_id = p_lega_id;
  delete from leghe where id = p_lega_id;
  return 'ok';
end;
$$;
