-- ============================================================
-- SCARSI LEAGUE — Migrazione v1.16 — Community: commenti e reazioni
-- Eseguire nell'SQL Editor di Supabase dopo v21.sql
--
-- Prima funzionalità in cui un membro qualsiasi scrive contenuto
-- libero visibile agli altri membri della lega (finora l'app importa
-- solo statistiche, o lascia scrivere solo l'admin/coorganizzatore).
--
-- Commenti solo su partite già giocate: `partite` rappresenta
-- strutturalmente solo partite disputate (gol_squadra_* not null,
-- importate a cose fatte da Fubles), quindi il vincolo di chiave
-- esterna su partite(id) è già la garanzia che serve — nessun flag
-- "partita conclusa" aggiuntivo.
-- ============================================================

create table if not exists commenti_partita (
  id           bigint generated by default as identity primary key,
  partita_id   bigint not null references partite(id) on delete cascade,
  autore_email text not null references utenti_piattaforma(email),
  testo        text not null check (char_length(trim(testo)) between 1 and 500),
  creato_il    timestamptz not null default now()
);

create index if not exists idx_commenti_partita on commenti_partita (partita_id, creato_il);

create table if not exists reazioni_commento (
  id           bigint generated by default as identity primary key,
  commento_id  bigint not null references commenti_partita(id) on delete cascade,
  autore_email text not null references utenti_piattaforma(email),
  emoji        text not null check (emoji in ('😂','🔥','😭','🤡','👏','💪')),
  creato_il    timestamptz not null default now(),
  unique (commento_id, autore_email)
);

alter table commenti_partita enable row level security;
alter table reazioni_commento enable row level security;

do $$
declare pol record; t text;
begin
  foreach t in array array['commenti_partita','reazioni_commento'] loop
    for pol in select policyname from pg_policies where schemaname = 'public' and tablename = t loop
      execute format('drop policy %I on %I', pol.policyname, t);
    end loop;
  end loop;
end $$;

-- commenti_partita: lettura per i membri della lega (dedotta via partite),
-- scrittura/cancellazione del proprio commento, gestore modera tutto
create policy "lettura membri" on commenti_partita for select to authenticated
  using (exists (select 1 from partite pt where pt.id = commenti_partita.partita_id and is_membro_lega(pt.lega_id)));

create policy "membro scrive proprio commento" on commenti_partita for insert to authenticated
  with check (
    autore_email = lower(auth.jwt() ->> 'email')
    and exists (select 1 from partite pt where pt.id = commenti_partita.partita_id and is_membro_lega(pt.lega_id))
  );
create policy "membro elimina proprio commento" on commenti_partita for delete to authenticated
  using (autore_email = lower(auth.jwt() ->> 'email'));

create policy "gestore modera commenti" on commenti_partita for all to authenticated
  using (exists (select 1 from partite pt where pt.id = commenti_partita.partita_id and is_gestore_lega(pt.lega_id)))
  with check (exists (select 1 from partite pt where pt.id = commenti_partita.partita_id and is_gestore_lega(pt.lega_id)));

-- reazioni_commento: lega dedotta commento -> partita
create policy "lettura membri" on reazioni_commento for select to authenticated
  using (exists (
    select 1 from commenti_partita c join partite pt on pt.id = c.partita_id
    where c.id = reazioni_commento.commento_id and is_membro_lega(pt.lega_id)
  ));
create policy "membro gestisce propria reazione" on reazioni_commento for all to authenticated
  using (autore_email = lower(auth.jwt() ->> 'email'))
  with check (
    autore_email = lower(auth.jwt() ->> 'email')
    and exists (
      select 1 from commenti_partita c join partite pt on pt.id = c.partita_id
      where c.id = reazioni_commento.commento_id and is_membro_lega(pt.lega_id)
    )
  );
create policy "gestore modera reazioni" on reazioni_commento for delete to authenticated
  using (exists (
    select 1 from commenti_partita c join partite pt on pt.id = c.partita_id
    where c.id = reazioni_commento.commento_id and is_gestore_lega(pt.lega_id)
  ));

-- ---------- helper condiviso, servirà anche a sondaggi e pronostici ----------
-- risolve email -> nome da mostrare + foto, coprendo anche i membri che
-- non hanno reclamato nessuna scheda giocatore (giocatore_id nullable)
create or replace function membri_display(p_lega_id bigint)
returns table(email text, nome_visualizzato text, foto_url text)
language sql security definer stable as $$
  select m.email,
         coalesce(g.nickname, g.nome, nullif(trim(concat_ws(' ', u.nome, u.cognome)), ''), split_part(m.email, '@', 1)) as nome_visualizzato,
         g.foto_url
  from membri_autorizzati m
  left join giocatori g on g.id = m.giocatore_id
  left join utenti_piattaforma u on u.email = m.email
  where m.lega_id = p_lega_id and is_membro_lega(p_lega_id);
$$;

-- ---------- elimina_lega(): ripulisce anche commenti/reazioni prima di partite ----------
create or replace function elimina_lega(p_lega_id bigint) returns text
language plpgsql security definer as $$
begin
  if not is_admin_lega(p_lega_id) then return 'Non autorizzato'; end if;

  delete from reazioni_commento where commento_id in (
    select c.id from commenti_partita c join partite pt on pt.id = c.partita_id where pt.lega_id = p_lega_id);
  delete from commenti_partita where partita_id in (select id from partite where lega_id = p_lega_id);
  delete from voti_ricevuti where partita_id in (select id from partite where lega_id = p_lega_id);
  delete from dati_manuali where partita_id in (select id from partite where lega_id = p_lega_id);
  delete from prestazioni where partita_id in (select id from partite where lega_id = p_lega_id);
  delete from premi where lega_id = p_lega_id;
  delete from partite where lega_id = p_lega_id;
  delete from stagioni where lega_id = p_lega_id;
  delete from membri_autorizzati where lega_id = p_lega_id;
  delete from richieste_accesso where lega_id = p_lega_id;
  delete from dati_organizzativi where lega_id = p_lega_id;
  delete from giocatori where lega_id = p_lega_id;
  delete from leghe where id = p_lega_id;
  return 'ok';
end;
$$;
