-- ============================================================
-- SCARSI LEAGUE — Migrazione v1.17 — Community: sondaggi
-- Eseguire nell'SQL Editor di Supabase dopo v22.sql
-- ============================================================

create table if not exists sondaggi (
  id            bigint generated by default as identity primary key,
  lega_id       bigint not null references leghe(id) on delete cascade,
  domanda       text not null check (char_length(trim(domanda)) between 1 and 200),
  stato         text not null default 'aperto' check (stato in ('aperto', 'chiuso')),
  creato_da_email text not null references utenti_piattaforma(email),
  creato_il     timestamptz not null default now()
);
create index if not exists idx_sondaggi_lega on sondaggi (lega_id, creato_il desc);

create table if not exists opzioni_sondaggio (
  id            bigint generated by default as identity primary key,
  sondaggio_id  bigint not null references sondaggi(id) on delete cascade,
  testo         text not null check (char_length(trim(testo)) between 1 and 100)
);
create index if not exists idx_opzioni_sondaggio on opzioni_sondaggio (sondaggio_id);

create table if not exists voti_sondaggio (
  id            bigint generated by default as identity primary key,
  sondaggio_id  bigint not null references sondaggi(id) on delete cascade,
  opzione_id    bigint not null references opzioni_sondaggio(id) on delete cascade,
  autore_email  text not null references utenti_piattaforma(email),
  creato_il     timestamptz not null default now(),
  unique (sondaggio_id, autore_email)
);
create index if not exists idx_voti_sondaggio on voti_sondaggio (sondaggio_id);

alter table sondaggi enable row level security;
alter table opzioni_sondaggio enable row level security;
alter table voti_sondaggio enable row level security;

do $$
declare pol record;
begin
  for pol in select policyname from pg_policies where schemaname = 'public' and tablename = 'sondaggi' loop
    execute format('drop policy %I on sondaggi', pol.policyname);
  end loop;
  for pol in select policyname from pg_policies where schemaname = 'public' and tablename = 'opzioni_sondaggio' loop
    execute format('drop policy %I on opzioni_sondaggio', pol.policyname);
  end loop;
  for pol in select policyname from pg_policies where schemaname = 'public' and tablename = 'voti_sondaggio' loop
    execute format('drop policy %I on voti_sondaggio', pol.policyname);
  end loop;
end $$;

create policy "lettura membri" on sondaggi for select to authenticated
  using (is_membro_lega(lega_id));
create policy "gestore crea sondaggio" on sondaggi for insert to authenticated
  with check (is_gestore_lega(lega_id) and creato_da_email = lower(auth.jwt() ->> 'email'));
create policy "gestore modifica sondaggio" on sondaggi for update to authenticated
  using (is_gestore_lega(lega_id)) with check (is_gestore_lega(lega_id));
create policy "gestore elimina sondaggio" on sondaggi for delete to authenticated
  using (is_gestore_lega(lega_id));

create policy "lettura membri" on opzioni_sondaggio for select to authenticated
  using (exists (select 1 from sondaggi s where s.id = opzioni_sondaggio.sondaggio_id and is_membro_lega(s.lega_id)));
create policy "gestore scrive opzioni" on opzioni_sondaggio for all to authenticated
  using (exists (select 1 from sondaggi s where s.id = opzioni_sondaggio.sondaggio_id and is_gestore_lega(s.lega_id)))
  with check (exists (select 1 from sondaggi s where s.id = opzioni_sondaggio.sondaggio_id and is_gestore_lega(s.lega_id)));

create policy "lettura membri" on voti_sondaggio for select to authenticated
  using (exists (select 1 from sondaggi s where s.id = voti_sondaggio.sondaggio_id and is_membro_lega(s.lega_id)));
create policy "membro vota" on voti_sondaggio for insert to authenticated
  with check (
    autore_email = lower(auth.jwt() ->> 'email')
    and exists (select 1 from sondaggi s where s.id = voti_sondaggio.sondaggio_id and is_membro_lega(s.lega_id) and s.stato = 'aperto')
  );
create policy "membro cambia voto" on voti_sondaggio for update to authenticated
  using (autore_email = lower(auth.jwt() ->> 'email'))
  with check (
    autore_email = lower(auth.jwt() ->> 'email')
    and exists (select 1 from sondaggi s where s.id = voti_sondaggio.sondaggio_id and s.stato = 'aperto')
  );
create policy "gestore modera voti" on voti_sondaggio for delete to authenticated
  using (exists (select 1 from sondaggi s where s.id = voti_sondaggio.sondaggio_id and is_gestore_lega(s.lega_id)));

create or replace function elimina_lega(p_lega_id bigint) returns text
language plpgsql security definer as $$
begin
  if not is_admin_lega(p_lega_id) then return 'Non autorizzato'; end if;
  delete from voti_sondaggio where sondaggio_id in (select id from sondaggi where lega_id = p_lega_id);
  delete from opzioni_sondaggio where sondaggio_id in (select id from sondaggi where lega_id = p_lega_id);
  delete from sondaggi where lega_id = p_lega_id;
  delete from reazioni_commento where commento_id in (select c.id from commenti_partita c join partite pt on pt.id = c.partita_id where pt.lega_id = p_lega_id);
  delete from commenti_partita where partita_id in (select id from partite where lega_id = p_lega_id);
  delete from voti_ricevuti where partita_id in (select id from partite where lega_id = p_lega_id);
  delete from dati_manuali where partita_id in (select id from partite where lega_id = p_lega_id);
  delete from prestazioni where partita_id in (select id from partite where lega_id = p_lega_id);
  delete from premi where lega_id = p_lega_id;
  delete from partite where lega_id = p_lega_id;
  delete from stagioni where lega_id = p_lega_id;
  delete from membri_autorizzati where lega_id = p_lega_id;
  delete from richieste_accesso where lega_id = p_lega_id;
  delete from dati_organizzativi where lega_id = p_lega_id;
  delete from giocatori where lega_id = p_lega_id;
  delete from leghe where id = p_lega_id;
  return 'ok';
end;
$$;
