-- ============================================================
-- SCARSI LEAGUE — Migrazione v1.18 — Notifiche push (web push)
-- Eseguire nell'SQL Editor di Supabase dopo v23.sql
-- ============================================================

create table if not exists push_subscriptions (
  id         bigint generated by default as identity primary key,
  email      text not null references utenti_piattaforma(email),
  endpoint   text not null unique,
  p256dh     text not null,
  auth       text not null,
  creato_il  timestamptz not null default now()
);
create index if not exists idx_push_subscriptions_email on push_subscriptions (email);

alter table push_subscriptions enable row level security;

do $$
declare pol record;
begin
  for pol in select policyname from pg_policies where schemaname = 'public' and tablename = 'push_subscriptions' loop
    execute format('drop policy %I on push_subscriptions', pol.policyname);
  end loop;
end $$;

create policy "gestisce proprie subscription" on push_subscriptions for all to authenticated
  using (email = lower(auth.jwt() ->> 'email'))
  with check (email = lower(auth.jwt() ->> 'email'));
