-- ============================================================
-- SCARSI LEAGUE — Migrazione v1.20 — Capitani per partita (FASE B)
-- Eseguire nell'SQL Editor di Supabase dopo v24.sql
-- ============================================================

-- correzione manuale dei gol: mai toccata dall'import Fubles (a
-- differenza di prestazioni.gol, sovrascritto a ogni re-import), le
-- classifiche la useranno al posto del dato Fubles quando presente
alter table dati_manuali add column if not exists gol_manuale smallint;

create table if not exists capitani_partita (
  id           bigint generated by default as identity primary key,
  partita_id   bigint not null references partite(id) on delete cascade,
  squadra      text not null,
  email        text not null references utenti_piattaforma(email),
  assegnato_il timestamptz not null default now(),
  unique (partita_id, squadra)
);
create index if not exists idx_capitani_partita on capitani_partita (partita_id);

alter table capitani_partita enable row level security;

do $$
declare pol record;
begin
  for pol in select policyname from pg_policies where schemaname = 'public' and tablename = 'capitani_partita' loop
    execute format('drop policy %I on capitani_partita', pol.policyname);
  end loop;
end $$;

create policy "lettura membri" on capitani_partita for select to authenticated
  using (is_gestore_lega((select p.lega_id from partite p where p.id = capitani_partita.partita_id))
    or exists (select 1 from partite p where p.id = capitani_partita.partita_id and is_membro_lega(p.lega_id)));
create policy "gestore assegna capitani" on capitani_partita for all to authenticated
  using (is_gestore_lega((select p.lega_id from partite p where p.id = capitani_partita.partita_id)))
  with check (is_gestore_lega((select p.lega_id from partite p where p.id = capitani_partita.partita_id)));

-- true se l'utente corrente è il capitano assegnato a quella squadra, in quella partita
create or replace function is_capitano_partita(p_partita_id bigint, p_squadra text) returns boolean
language sql security definer stable as $$
  select exists (
    select 1 from capitani_partita c
    where c.partita_id = p_partita_id and c.squadra = p_squadra
      and c.email = lower(auth.jwt() ->> 'email')
  );
$$;

-- dati_manuali: il gestore mantiene accesso completo (invariato), un
-- capitano ottiene accesso solo ai giocatori della propria squadra in
-- quella specifica partita (join su prestazioni.squadra)
do $$
declare pol record;
begin
  for pol in select policyname from pg_policies where schemaname = 'public' and tablename = 'dati_manuali' loop
    execute format('drop policy %I on dati_manuali', pol.policyname);
  end loop;
end $$;

create policy "lettura membri" on dati_manuali for select to authenticated
  using (exists (select 1 from partite p where p.id = dati_manuali.partita_id and is_membro_lega(p.lega_id)));
create policy "gestore scrive dati manuali" on dati_manuali for all to authenticated
  using (is_gestore_lega((select p.lega_id from partite p where p.id = dati_manuali.partita_id)))
  with check (is_gestore_lega((select p.lega_id from partite p where p.id = dati_manuali.partita_id)));
create policy "capitano modifica propria squadra" on dati_manuali for all to authenticated
  using (exists (
    select 1 from prestazioni pr
    where pr.partita_id = dati_manuali.partita_id and pr.giocatore_id = dati_manuali.giocatore_id
      and is_capitano_partita(pr.partita_id, pr.squadra)
  ))
  with check (exists (
    select 1 from prestazioni pr
    where pr.partita_id = dati_manuali.partita_id and pr.giocatore_id = dati_manuali.giocatore_id
      and is_capitano_partita(pr.partita_id, pr.squadra)
  ));

-- elimina_lega(): ripulisce anche capitani_partita prima di partite
create or replace function elimina_lega(p_lega_id bigint) returns text
language plpgsql security definer as $$
begin
  if not is_admin_lega(p_lega_id) then return 'Non autorizzato'; end if;
  delete from capitani_partita where partita_id in (select id from partite where lega_id = p_lega_id);
  delete from voti_sondaggio where sondaggio_id in (select id from sondaggi where lega_id = p_lega_id);
  delete from opzioni_sondaggio where sondaggio_id in (select id from sondaggi where lega_id = p_lega_id);
  delete from sondaggi where lega_id = p_lega_id;
  delete from reazioni_commento where commento_id in (select c.id from commenti_partita c join partite pt on pt.id = c.partita_id where pt.lega_id = p_lega_id);
  delete from commenti_partita where partita_id in (select id from partite where lega_id = p_lega_id);
  delete from voti_ricevuti where partita_id in (select id from partite where lega_id = p_lega_id);
  delete from dati_manuali where partita_id in (select id from partite where lega_id = p_lega_id);
  delete from prestazioni where partita_id in (select id from partite where lega_id = p_lega_id);
  delete from premi where lega_id = p_lega_id;
  delete from partite where lega_id = p_lega_id;
  delete from stagioni where lega_id = p_lega_id;
  delete from membri_autorizzati where lega_id = p_lega_id;
  delete from richieste_accesso where lega_id = p_lega_id;
  delete from dati_organizzativi where lega_id = p_lega_id;
  delete from giocatori where lega_id = p_lega_id;
  delete from leghe where id = p_lega_id;
  return 'ok';
end;
$$;
