-- ============================================================
-- SCARSI LEAGUE — Migrazione v1.21 — Proposte incrociate capitani (FASE C)
-- Eseguire nell'SQL Editor di Supabase dopo v25.sql
-- ============================================================

-- proposta di correzione dati che un capitano invia per un giocatore
-- della squadra AVVERSARIA: resta in sospeso finché il capitano di
-- quella squadra (o il gestore) non la approva o rifiuta. L'approvazione
-- copia i valori in dati_manuali (stessa forma di dati_manuali + gol_manuale).
create table if not exists dati_manuali_proposte (
  id               bigint generated by default as identity primary key,
  partita_id       bigint not null references partite(id) on delete cascade,
  giocatore_id     bigint not null references giocatori(id) on delete cascade,
  gol_manuale      smallint,
  assist           smallint not null default 0,
  clean_sheet      boolean not null default false,
  gol_subiti       smallint,
  cartellini       smallint not null default 0,
  autogol          smallint not null default 0,
  note             text,
  proposto_da_email text not null references utenti_piattaforma(email),
  stato            text not null default 'in_attesa' check (stato in ('in_attesa', 'approvata', 'rifiutata')),
  gestito_da_email text references utenti_piattaforma(email),
  gestito_il       timestamptz,
  creato_il        timestamptz not null default now()
);
create index if not exists idx_dati_manuali_proposte_partita on dati_manuali_proposte (partita_id);

-- un solo giocatore può avere al più una proposta in sospeso alla volta
create unique index if not exists dati_manuali_proposte_pendenti_uniq
  on dati_manuali_proposte (partita_id, giocatore_id) where stato = 'in_attesa';

alter table dati_manuali_proposte enable row level security;

do $$
declare pol record;
begin
  for pol in select policyname from pg_policies where schemaname = 'public' and tablename = 'dati_manuali_proposte' loop
    execute format('drop policy %I on dati_manuali_proposte', pol.policyname);
  end loop;
end $$;

-- lettura: chi ha proposto, il capitano della squadra bersaglio, o il gestore
create policy "vedi le tue proposte" on dati_manuali_proposte for select to authenticated
  using (
    proposto_da_email = lower(auth.jwt() ->> 'email')
    or is_gestore_lega((select p.lega_id from partite p where p.id = dati_manuali_proposte.partita_id))
    or exists (
      select 1 from prestazioni pr
      where pr.partita_id = dati_manuali_proposte.partita_id and pr.giocatore_id = dati_manuali_proposte.giocatore_id
        and is_capitano_partita(pr.partita_id, pr.squadra)
    )
  );

-- inserimento: solo un capitano di questa partita, e solo per un
-- giocatore della squadra DIVERSA dalla propria
create policy "capitano propone per l'altra squadra" on dati_manuali_proposte for insert to authenticated
  with check (
    proposto_da_email = lower(auth.jwt() ->> 'email')
    and stato = 'in_attesa'
    and exists (
      select 1 from capitani_partita c
      join prestazioni pr on pr.partita_id = c.partita_id and pr.giocatore_id = dati_manuali_proposte.giocatore_id
      where c.partita_id = dati_manuali_proposte.partita_id
        and c.email = lower(auth.jwt() ->> 'email')
        and c.squadra <> pr.squadra
    )
  );

-- nessuna policy di update/delete: l'approvazione/rifiuto passa solo
-- dalle RPC qui sotto (security definer, bypassano la RLS dopo aver
-- controllato a mano l'autorizzazione)

create or replace function approva_proposta_dati(p_id bigint) returns text
language plpgsql security definer as $$
declare v_prop record;
begin
  select * into v_prop from dati_manuali_proposte where id = p_id;
  if v_prop is null then return 'Proposta non trovata'; end if;
  if v_prop.stato <> 'in_attesa' then return 'Proposta già gestita'; end if;
  if not (
    is_gestore_lega((select p.lega_id from partite p where p.id = v_prop.partita_id))
    or is_capitano_partita(v_prop.partita_id, (
      select pr.squadra from prestazioni pr
      where pr.partita_id = v_prop.partita_id and pr.giocatore_id = v_prop.giocatore_id
    ))
  ) then
    return 'Non autorizzato';
  end if;

  insert into dati_manuali (partita_id, giocatore_id, gol_manuale, assist, clean_sheet, gol_subiti, cartellini, autogol, note)
    values (v_prop.partita_id, v_prop.giocatore_id, v_prop.gol_manuale, v_prop.assist, v_prop.clean_sheet, v_prop.gol_subiti, v_prop.cartellini, v_prop.autogol, v_prop.note)
  on conflict (partita_id, giocatore_id) do update set
    gol_manuale = excluded.gol_manuale, assist = excluded.assist, clean_sheet = excluded.clean_sheet,
    gol_subiti = excluded.gol_subiti, cartellini = excluded.cartellini, autogol = excluded.autogol, note = excluded.note;

  update dati_manuali_proposte set stato = 'approvata', gestito_da_email = lower(auth.jwt() ->> 'email'), gestito_il = now()
    where id = p_id;
  return 'ok';
end;
$$;

create or replace function rifiuta_proposta_dati(p_id bigint) returns text
language plpgsql security definer as $$
declare v_prop record;
begin
  select * into v_prop from dati_manuali_proposte where id = p_id;
  if v_prop is null then return 'Proposta non trovata'; end if;
  if v_prop.stato <> 'in_attesa' then return 'Proposta già gestita'; end if;
  if not (
    is_gestore_lega((select p.lega_id from partite p where p.id = v_prop.partita_id))
    or is_capitano_partita(v_prop.partita_id, (
      select pr.squadra from prestazioni pr
      where pr.partita_id = v_prop.partita_id and pr.giocatore_id = v_prop.giocatore_id
    ))
  ) then
    return 'Non autorizzato';
  end if;

  update dati_manuali_proposte set stato = 'rifiutata', gestito_da_email = lower(auth.jwt() ->> 'email'), gestito_il = now()
    where id = p_id;
  return 'ok';
end;
$$;

-- elimina_lega(): ripulisce anche dati_manuali_proposte prima di dati_manuali
create or replace function elimina_lega(p_lega_id bigint) returns text
language plpgsql security definer as $$
begin
  if not is_admin_lega(p_lega_id) then return 'Non autorizzato'; end if;
  delete from dati_manuali_proposte where partita_id in (select id from partite where lega_id = p_lega_id);
  delete from capitani_partita where partita_id in (select id from partite where lega_id = p_lega_id);
  delete from voti_sondaggio where sondaggio_id in (select id from sondaggi where lega_id = p_lega_id);
  delete from opzioni_sondaggio where sondaggio_id in (select id from sondaggi where lega_id = p_lega_id);
  delete from sondaggi where lega_id = p_lega_id;
  delete from reazioni_commento where commento_id in (select c.id from commenti_partita c join partite pt on pt.id = c.partita_id where pt.lega_id = p_lega_id);
  delete from commenti_partita where partita_id in (select id from partite where lega_id = p_lega_id);
  delete from voti_ricevuti where partita_id in (select id from partite where lega_id = p_lega_id);
  delete from dati_manuali where partita_id in (select id from partite where lega_id = p_lega_id);
  delete from prestazioni where partita_id in (select id from partite where lega_id = p_lega_id);
  delete from premi where lega_id = p_lega_id;
  delete from partite where lega_id = p_lega_id;
  delete from stagioni where lega_id = p_lega_id;
  delete from membri_autorizzati where lega_id = p_lega_id;
  delete from richieste_accesso where lega_id = p_lega_id;
  delete from dati_organizzativi where lega_id = p_lega_id;
  delete from giocatori where lega_id = p_lega_id;
  delete from leghe where id = p_lega_id;
  return 'ok';
end;
$$;
