-- ============================================================
-- SCARSI LEAGUE — Migrazione v1.23 — Campanella notifiche in-app
-- Eseguire nell'SQL Editor di Supabase dopo v26.sql
-- ============================================================

-- storico in-app degli stessi eventi già coperti dalla push del
-- browser: scritto lato server (service role, bypassa la RLS) nella
-- stessa route /api/push/send, cosicché resti l'unica fonte di verità
-- per chi-riceve-cosa. A differenza della push, non richiede opt-in.
create table if not exists notifiche (
  id         bigint generated by default as identity primary key,
  email      text not null references utenti_piattaforma(email),
  titolo     text not null,
  corpo      text,
  url        text,
  letta      boolean not null default false,
  creato_il  timestamptz not null default now()
);
create index if not exists idx_notifiche_email on notifiche (email, creato_il desc);

alter table notifiche enable row level security;

do $$
declare pol record;
begin
  for pol in select policyname from pg_policies where schemaname = 'public' and tablename = 'notifiche' loop
    execute format('drop policy %I on notifiche', pol.policyname);
  end loop;
end $$;

create policy "vedi le tue notifiche" on notifiche for select to authenticated
  using (email = lower(auth.jwt() ->> 'email'));
create policy "segna come letta la tua notifica" on notifiche for update to authenticated
  using (email = lower(auth.jwt() ->> 'email'))
  with check (email = lower(auth.jwt() ->> 'email'));

-- nessuna policy di insert/delete: la scrittura avviene solo lato
-- server con la service role key, che bypassa comunque la RLS

alter publication supabase_realtime add table notifiche;
