-- ============================================================
-- SCARSI LEAGUE — Migrazione v1.25 — Voto capitani, FASE A: infrastruttura
-- Eseguire nell'SQL Editor di Supabase dopo v27.sql
-- ============================================================

-- peso del voto capitano per stagione: null = disattivato (default),
-- nessuna lega/stagione è obbligata ad attivare i capitani sui voti.
-- Impostabile solo per stagione (non per lega intera) perché una lega
-- può iniziare a usare i capitani da una certa stagione in poi, mai
-- retroattivamente su quelle passate.
alter table stagioni add column if not exists peso_voto_capitano smallint;

-- voto che un capitano dà a un giocatore della squadra AVVERSARIA
-- (mai ai propri compagni): giudizio diretto, non richiede approvazione
-- come le correzioni gol/assist in dati_manuali_proposte.
create table if not exists voti_capitano (
  id             bigint generated by default as identity primary key,
  partita_id     bigint not null references partite(id) on delete cascade,
  giocatore_id   bigint not null references giocatori(id) on delete cascade,
  voto           numeric not null check (voto >= 1 and voto <= 10),
  capitano_email text not null references utenti_piattaforma(email),
  creato_il      timestamptz not null default now(),
  unique (partita_id, giocatore_id)
);
create index if not exists idx_voti_capitano_partita on voti_capitano (partita_id);

alter table voti_capitano enable row level security;

do $$
declare pol record;
begin
  for pol in select policyname from pg_policies where schemaname = 'public' and tablename = 'voti_capitano' loop
    execute format('drop policy %I on voti_capitano', pol.policyname);
  end loop;
end $$;

create policy "lettura membri" on voti_capitano for select to authenticated
  using (exists (select 1 from partite p where p.id = voti_capitano.partita_id and is_membro_lega(p.lega_id)));
create policy "gestore scrive voti capitano" on voti_capitano for all to authenticated
  using (is_gestore_lega((select p.lega_id from partite p where p.id = voti_capitano.partita_id)))
  with check (is_gestore_lega((select p.lega_id from partite p where p.id = voti_capitano.partita_id)));
-- il capitano vota solo giocatori della squadra DIVERSA dalla propria
create policy "capitano vota gli avversari" on voti_capitano for all to authenticated
  using (
    capitano_email = lower(auth.jwt() ->> 'email')
    and exists (
      select 1 from capitani_partita c
      join prestazioni pr on pr.partita_id = c.partita_id and pr.giocatore_id = voti_capitano.giocatore_id
      where c.partita_id = voti_capitano.partita_id
        and c.email = lower(auth.jwt() ->> 'email')
        and c.squadra <> pr.squadra
    )
  )
  with check (
    capitano_email = lower(auth.jwt() ->> 'email')
    and exists (
      select 1 from capitani_partita c
      join prestazioni pr on pr.partita_id = c.partita_id and pr.giocatore_id = voti_capitano.giocatore_id
      where c.partita_id = voti_capitano.partita_id
        and c.email = lower(auth.jwt() ->> 'email')
        and c.squadra <> pr.squadra
    )
  );

-- voti_ricevuti: il capitano può moderare (escludere/ripristinare) solo
-- i voti CASTATI da un proprio compagno di squadra in quella partita —
-- non tocca chi li ha ricevuti, solo l'affidabilità di chi li ha dati.
-- Le policy "gestore scrive"/"lettura membri" esistenti restano invariate.
create policy "capitano modera voti dei propri compagni" on voti_ricevuti for update to authenticated
  using (exists (
    select 1 from prestazioni pr
    where pr.partita_id = voti_ricevuti.partita_id and pr.giocatore_id = voti_ricevuti.votante_id
      and is_capitano_partita(pr.partita_id, pr.squadra)
  ))
  with check (exists (
    select 1 from prestazioni pr
    where pr.partita_id = voti_ricevuti.partita_id and pr.giocatore_id = voti_ricevuti.votante_id
      and is_capitano_partita(pr.partita_id, pr.squadra)
  ));

-- elimina_lega(): ripulisce anche voti_capitano prima di partite
create or replace function elimina_lega(p_lega_id bigint) returns text
language plpgsql security definer as $$
begin
  if not is_admin_lega(p_lega_id) then return 'Non autorizzato'; end if;
  delete from voti_capitano where partita_id in (select id from partite where lega_id = p_lega_id);
  delete from dati_manuali_proposte where partita_id in (select id from partite where lega_id = p_lega_id);
  delete from capitani_partita where partita_id in (select id from partite where lega_id = p_lega_id);
  delete from voti_sondaggio where sondaggio_id in (select id from sondaggi where lega_id = p_lega_id);
  delete from opzioni_sondaggio where sondaggio_id in (select id from sondaggi where lega_id = p_lega_id);
  delete from sondaggi where lega_id = p_lega_id;
  delete from reazioni_commento where commento_id in (select c.id from commenti_partita c join partite pt on pt.id = c.partita_id where pt.lega_id = p_lega_id);
  delete from commenti_partita where partita_id in (select id from partite where lega_id = p_lega_id);
  delete from voti_ricevuti where partita_id in (select id from partite where lega_id = p_lega_id);
  delete from dati_manuali where partita_id in (select id from partite where lega_id = p_lega_id);
  delete from prestazioni where partita_id in (select id from partite where lega_id = p_lega_id);
  delete from premi where lega_id = p_lega_id;
  delete from partite where lega_id = p_lega_id;
  delete from stagioni where lega_id = p_lega_id;
  delete from membri_autorizzati where lega_id = p_lega_id;
  delete from richieste_accesso where lega_id = p_lega_id;
  delete from dati_organizzativi where lega_id = p_lega_id;
  delete from giocatori where lega_id = p_lega_id;
  delete from leghe where id = p_lega_id;
  return 'ok';
end;
$$;
