-- ============================================================
-- SCARSI LEAGUE — Migrazione v1.28 — Live match, FASE A: infrastruttura
-- Eseguire nell'SQL Editor di Supabase dopo v28.sql
-- ============================================================

-- una partita "normale" (importata come sempre, a giochi fatti) non
-- tocca mai queste colonne: null ovunque, comportamento identico a oggi.
-- stato_live è deliberatamente separato dalla colonna "stato" già
-- esistente (scritta solo dall'import Excel con valori liberi tipo
-- "Disputata" letti da Fubles, mai usata dall'app) per non confondere
-- un dato passivo di Fubles con uno stato macchina che gestiamo noi.
alter table partite add column if not exists stato_live text
  check (stato_live in ('programmata', 'in_corso', 'conclusa'));
alter table partite add column if not exists condivisione_pubblica boolean not null default false;
alter table partite add column if not exists codice_live text unique;

-- una partita pre-match non ha ancora un risultato
alter table partite alter column gol_squadra_1 drop not null;
alter table partite alter column gol_squadra_2 drop not null;

-- il cronista copre l'intera partita (entrambe le squadre), a
-- differenza del capitano che è legato a una squadra sola — nessuna
-- colonna squadra qui.
create table if not exists cronisti_partita (
  id           bigint generated by default as identity primary key,
  partita_id   bigint not null references partite(id) on delete cascade,
  email        text not null references utenti_piattaforma(email),
  assegnato_il timestamptz not null default now(),
  unique (partita_id, email)
);
create index if not exists idx_cronisti_partita on cronisti_partita (partita_id);

alter table cronisti_partita enable row level security;

do $$
declare pol record;
begin
  for pol in select policyname from pg_policies where schemaname = 'public' and tablename = 'cronisti_partita' loop
    execute format('drop policy %I on cronisti_partita', pol.policyname);
  end loop;
end $$;

create policy "lettura membri" on cronisti_partita for select to authenticated
  using (exists (select 1 from partite p where p.id = cronisti_partita.partita_id and is_membro_lega(p.lega_id)));
create policy "gestore assegna cronisti" on cronisti_partita for all to authenticated
  using (is_gestore_lega((select p.lega_id from partite p where p.id = cronisti_partita.partita_id)))
  with check (is_gestore_lega((select p.lega_id from partite p where p.id = cronisti_partita.partita_id)));

-- true se l'utente corrente è il cronista assegnato a questa partita
create or replace function is_cronista_partita(p_partita_id bigint) returns boolean
language sql security definer stable as $$
  select exists (
    select 1 from cronisti_partita c
    where c.partita_id = p_partita_id and c.email = lower(auth.jwt() ->> 'email')
  );
$$;

-- dati_manuali: il cronista scrive per QUALSIASI giocatore della
-- partita (non solo la propria squadra, come invece vale per il
-- capitano) — le altre policy esistenti (gestore, capitano) restano
-- invariate.
create policy "cronista scrive durante la partita" on dati_manuali for all to authenticated
  using (is_cronista_partita(dati_manuali.partita_id))
  with check (is_cronista_partita(dati_manuali.partita_id));

-- prestazioni: il cronista può creare/spostare/rimuovere righe per
-- aggiustare la formazione pre-match (chi gioca, in quale squadra) —
-- le policy esistenti (gestore) restano invariate.
create policy "cronista gestisce la formazione" on prestazioni for all to authenticated
  using (is_cronista_partita(prestazioni.partita_id))
  with check (is_cronista_partita(prestazioni.partita_id));

-- elimina_lega(): ripulisce anche cronisti_partita prima di partite
create or replace function elimina_lega(p_lega_id bigint) returns text
language plpgsql security definer as $$
begin
  if not is_admin_lega(p_lega_id) then return 'Non autorizzato'; end if;
  delete from cronisti_partita where partita_id in (select id from partite where lega_id = p_lega_id);
  delete from voti_capitano where partita_id in (select id from partite where lega_id = p_lega_id);
  delete from dati_manuali_proposte where partita_id in (select id from partite where lega_id = p_lega_id);
  delete from capitani_partita where partita_id in (select id from partite where lega_id = p_lega_id);
  delete from voti_sondaggio where sondaggio_id in (select id from sondaggi where lega_id = p_lega_id);
  delete from opzioni_sondaggio where sondaggio_id in (select id from sondaggi where lega_id = p_lega_id);
  delete from sondaggi where lega_id = p_lega_id;
  delete from reazioni_commento where commento_id in (select c.id from commenti_partita c join partite pt on pt.id = c.partita_id where pt.lega_id = p_lega_id);
  delete from commenti_partita where partita_id in (select id from partite where lega_id = p_lega_id);
  delete from voti_ricevuti where partita_id in (select id from partite where lega_id = p_lega_id);
  delete from dati_manuali where partita_id in (select id from partite where lega_id = p_lega_id);
  delete from prestazioni where partita_id in (select id from partite where lega_id = p_lega_id);
  delete from premi where lega_id = p_lega_id;
  delete from partite where lega_id = p_lega_id;
  delete from stagioni where lega_id = p_lega_id;
  delete from membri_autorizzati where lega_id = p_lega_id;
  delete from richieste_accesso where lega_id = p_lega_id;
  delete from dati_organizzativi where lega_id = p_lega_id;
  delete from giocatori where lega_id = p_lega_id;
  delete from leghe where id = p_lega_id;
  return 'ok';
end;
$$;
